### ISSUE TITLE
Fails w/ exit code 1

### ISSUE THREAD

**Issue by clintmiller** [kielabokkie/ssh-key-and-known-hosts-action#28]
Is there any way to understand why the keyscan piece is failing?

```
Run kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
Starting ssh-agent
Adding private key
Adding host to known_hosts
Error: Command failed with exit code 1: ssh-keyscan -p 22 jumphostnamehere.com
```

Configured in workflow:
```
      - name: Setup SSH access to jumphost
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
        with:
          ssh-private-key: ${{ secrets.GHA_SSH_KEY }}
          ssh-host: ${{ vars.JUMP_HOST }}
          ssh-socket: /tmp/ssh_agent_${{ github.sha }}.sock
```
